[package]
name = "voice-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", default-features = false, features = ["macros", "net", "io-util", "rt-multi-thread"] }
local-ip-address = "0.6.5"
cpal = { version = "0.16.0" }

[features]
jack = ["cpal/jack"]